#!/bin/sh

window_id="$(xdotool search --class T560MusicPanel 2>/dev/null | tail -n 1)"
if [ -n "$window_id" ]; then
    xdotool windowmap "$window_id"
    xdotool windowraise "$window_id"
    xdotool windowactivate "$window_id"
else
    /usr/bin/t560-panel &
fi

